### ISSUE TITLE
de_sparity ice texture.

### ISSUE THREAD

**Issue by Au-lit** [Au-lit/WingmanContest2020#10]
Hum... how to make it work ?

**Comment by FuckWomen** [comment]
i don't know

**Comment by Au-lit** [comment]
Oh bah zut alors...


RECHERCE ESCLAVE.

**Comment by FuckWomen** [comment]
what Provenance : Courrier pour Windows 10 De : Au-litEnvoyé le :10 août 2020 13:02À : Au-lit/WingmanContest2020Cc : FuckWomen; AssignObjet :Re: [Au-lit/WingmanContest2020] de_sparity ice texture. (#10) Oh bah zut alors...RECHERCE ESCLAVE.—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Au-lit** [comment]
あの人ばかです。
